spring:
  security:
    oauth2:
      client:
        registration:
          oidcclient:
            client-id: spring-boot-client
            client-secret: <secret>
            client-name: OIDC Client
            provider: idp
            scope: openid
        provider:
          idp:
            issuer-uri: http://localhost:8081/auth/realms/spring-boot-demo
